### ISSUE TITLE
You are a thief it is not your blog you are not kept the rights of others

### ISSUE THREAD

**Issue by Gogo95** [MostafaAnter/YourStory#1]
it was a blog on medium for my friend Moyinoluwa Adeyemi it is not fair :)  ( https://goo.gl/c15ijy )

you can make your work by your hand although you can remove my comment but you can't remove bad ethics ,please learn and make your awesome work  =)

**Comment by MostafaAnter** [comment]
now i add your friend blog link and mentioned for her , but if you read my code its completely different, 
but its true my project based on your friend blog but i'm tried to translate and demonstrate that project for my community , sorry and thanks for your friend you can read readme file to check my mention :)
